# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def main():
    # Initialize first two numbers in the Fibonacci sequence
    num_1 = 1
    num_2 = 1

    # Holds even-values numbers in the Fibonacci sequence
    fib_sum = 0

    # Loop
    while num_2 < 4000000:
        # Find the next number in the sequence
        fib = num_1 + num_2

        # If the number is even, then add it to the sum value
        if fib % 2 == 0:
            fib_sum += fib

        # Reassign the values of lowest and highest numbers
        num_1 = num_2
        num_2 = fib

        print(fib)

    print("SUM IS: " + str(fib_sum))


if __name__ == '__main__':
    main()